[[redirects]] # настройки проксирования запросов на сервер
  from = "/api/*"
  to = "http://localhost:3000/:splat"
  status = 200

[[redirects]]
  from = "/server/*"
  to = "http://localhost:3000/:splat"
  status = 200